### ISSUE TITLE
Stuck at valve screen

### ISSUE THREAD

**Issue by PopTartsWasTaken** [JetLennit/hlalauncher#2]
When launching the game it gets stuck at a screen with the valve logo on it and the map wont load.

**Comment by JetLennit** [comment]
Hey! Out of curiosity, was this problem solved? If so, how?

**Comment by PopTartsWasTaken** [comment]
It wasn't solved but I asked on a discord server and you hadn't updated the project recently so I thought you abandoned it lol but I think its on my part.

**Comment by JetLennit** [comment]
Yeah, I had abandoned it because I figured that the workshop had already pretty much replaced any need for it. I'm kinda suprised people are still using to to be honest. Also, sorry about the "?!" in my last comment, not sure how that extra ! got there. If you want to talk through how to fix it my discord is in the readme, and I can try to provide all the support I can.
